kind: Service
apiVersion: v1
metadata:
  name: films
  labels:
    app: films
spec:
  selector:
    app: films
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: films
  labels:
    app: films
spec:
  replicas: 1
  selector:
    matchLabels:
      app: films
  template:
    metadata:
      labels:
        app: films
    spec:
      containers:
        - name: service
          image: films
          env:
            - name: "PORT"
              value: "50051"
          ports:
            - name: http
              containerPort: 50051