apiVersion: skaffold/v2beta12
kind: Config
build:
  local: {push: false}
  artifacts:
    - image: films
      context: ../../
      jib:
        project: films
        fromImage: gcr.io/distroless/java:11
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - k8s/*